name = "julifestxv"
compatibility_date = "2024-01-15"

[env.production]
name = "julifestxv"
routes = [
  { pattern = "julifestxv.aegre.me/*", custom_domain = true }
]

[[env.production.route]]
pattern = "julifestxv.aegre.me/*"
custom_domain = true 