name = "julifestxv"
compatibility_date = "2024-01-15"

# Database configuration
[[d1_databases]]
binding = "DB"
database_name = "julifestdb"
database_id = "1a40dfa5-1ed4-4ba3-9e6e-8f2da451af27"
preview_database_id = "1a40dfa5-1ed4-4ba3-9e6e-8f2da451af27"
migrations_dir = "database/migrations"

[env.production]
name = "julifestxv"
routes = [
  { pattern = "julifestxv.aegre.me/*", custom_domain = true }
]

# Production database configuration
[[env.production.d1_databases]]
binding = "DB"
database_name = "julifestdb-prod"
database_id = "8415ca5b-6ff3-4584-bb07-530bc99c814c" 